### ISSUE TITLE
Can you expand on the documentation?

### ISSUE THREAD

**Issue by jbranso** [mineo/yatemplate#11]
Thanks for writing this emacs extension!  It's pretty awesome!

But I really don't understand how to use it.  For example, I'm not sure how to create a file in yatemplate-dir that is used whenever I open an empty file in web-mode, or if the file ends in "php" or "html".  

Can you give a more elaborate code example that shows one how to do something like this?

**Comment by mineo** [comment]
Could you clarify which part of the currently existing documentation you're stuck at? As the author of something, it's always clear where something's not clear or only clear with some knowledge that's not explicitly stated anywhere. Note that the README currently assumes at least some knowledge about `auto-insert-mode`.

Regarding your examples: mode-specific templates are not possible (issue #1 is about that), but `00:.*.php` and `00:.*.html` should do the trick for the others.

**Comment by mineo** [comment]
I'm closing this because of a lock of reply. If there are still open questions, feel free to comment on this issue or open another one.
