### ISSUE TITLE
autoload cookies for safe local variables

### ISSUE THREAD

**Issue by fommil** [mineo/yatemplate#12]
This block of code could benefit from an autoload cookie so that the variables are considered safe before yatemplate is loaded.

```elisp
  (put 'yatemplate-owner 'safe-local-variable #'stringp)
  (put 'yatemplate-license 'safe-local-variable #'stringp)
```

**Comment by fommil** [comment]
Awesome! Sorry for being pathetic and not sending a PR, I was behind a corporate firewall.

**Comment by mineo** [comment]
Don't worry, I'll just ignore tickets if I don't have the time or desire to act on them ;-)
