### ISSUE TITLE
define some convention variables

### ISSUE THREAD

**Issue by fommil** [mineo/yatemplate#4]
it would be good if the following could be included as good practice variables for people to use

```elisp
(defvar-local yatemplate-owner user-full-name
  "The copyright owner for the buffer.
Particularly useful when combined with `dir-locals.el'.")

(defvar-local yatemplate-license "http://www.gnu.org/licenses/gpl.html"
  "The license (usually a URL) for the buffer.
It is always better to explicitly list the license per file than
to refer to the LICENSE file. Particularly useful when combined
with `dir-locals.el'.")
```

**Comment by fommil** [comment]
btw, you'd probably want to do this

```
(put 'yatemplate-owner 'safe-local-variable #'stringp)
(put 'yatemplate-license 'safe-local-variable #'stringp)
```

**Comment by mineo** [comment]
Are license URLs something people use? I'm only aware of "see LICENSE" or short GPL style notices at the beginning of source files.

**Comment by fommil** [comment]
you should not reference the LICENSE file because you are not guaranteed that the recipient will receive the full repository in context. Also, many people opt to avoid copying hundreds of lines of boilerplate into each file.

**Comment by mineo** [comment]
This took longer than it should have, but I've finally gotten around to adding those. I've not kept the hint about the LICENSE file because I don't feel comfortable making that statement with the small amount of knowledge about licensing and distributing (free) software that I have.

**Comment by fommil** [comment]
Cool thanks! Btw i don't think you needed to define them as local. Emacs does that automatically if the user is using Local-Variables, see you could use defcustom.
