### ISSUE TITLE
not possible to create templates in windows

### ISSUE THREAD

**Issue by fommil** [mineo/yatemplate#9]
It is not possible AFAICT to create files with names such as `50:*.el` on Windows 7.

Can you please support characters that are supported? Or allow the regex patterns to be defined by variables that refer to simple named files.

**Comment by fommil** [comment]
http://stackoverflow.com/questions/1976007/

**Comment by fommil** [comment]
is it possible to perhaps use the standard snippets format and put the regex pattern in the `name` field?

**Comment by fommil** [comment]
workaround

```
(let ((dir (concat user-emacs-directory "templates/")))
    (push `("\\.scala\\'" . [,(concat dir "scala") yatemplate-expand-yas-buffer]) auto-insert-alist)
    (push `("\\.el\\'" . [,(concat dir "emacs-lisp") yatemplate-expand-yas-buffer]) auto-insert-alist))
```

**Comment by mineo** [comment]
I'm sorry, but it's very unlikely that I'll change that part of the process. I simply do not care enough about Windows to invest time into figuring out a solution for it.
